### ISSUE TITLE
The code is incompatible with Algorithm1?

### ISSUE THREAD

**Issue by shuangshuangguo** [Hi-FT/ERD#4]
Hi, could you tell me where is the related code of computing the mean and std in the algorithm1?
I can not find it in mmdet/models/dense_heads/gfl_head_incre.py.

**Comment by chenfangchenf** [comment]
Did you have any problems during the first phase of training，I can't find fcos_head_tune...

**Comment by shuangshuangguo** [comment]
@chenfangchenf I just watch the code without training.

**Comment by satpalsr** [comment]
Hey @shuangshuangguo , did you train the model? What was your experience?
